<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="bootstrap-3.3.7/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="AdminLTE-2.4.3/bower_components/font-awesome/css/font-awesome.min.css">
        <link rel="stylesheet" href="my_styles/fonts.css">
        <link rel="stylesheet" href="AdminLTE-2.4.3/dist/css/AdminLTE.min.css">
        <link rel="stylesheet" href="AdminLTE-2.4.3/dist/css/skins/_all-skins.min.css">
        <link rel="stylesheet" href="my_styles/my_style_basic.css">
        <style>
            @media screen and (max-width: 767px) {
                .logout {
                    text-align: inherit;
                    width: inherit;
                    height: inherit;
                    margin-right: 0px;
                    margin-left: 0px;
                }
                .register-box {
                    margin-top: 65px;
                }
            } 

            .content{
                width: 100%;
                margin: 0;
                position: absolute;
                top: 50%;
                -ms-transform: translateY(-50%);
                transform: translateY(-50%);
                text-align: justify;
            }
            .imgLoginModal{
                max-width: 20%;
            }
        </style>
        <meta charset="utf-8">
        <meta name="robots" content="noindex">
        <title>Chyba - 500</title>
    </head>
    <body>
        <div class="content">

            <!-- Main content -->
            <section class="content">
                <img class="img img-responsive imgLoginModal" src="images/web/mainLogo.png" />
                <div class="error-page">
                    <h2 class="headline text-yellow">500</h2>

                    <div class="error-content">
                        <h3><i class="fa fa-warning text-yellow"></i> Oops! Chyba 500 - nezjištěná chyba webu - kontaktujte správce</h3>


                    </div>
                    <!-- /.error-content -->
                </div>
                <!-- /.error-page -->
            </section>
            <!-- /.content -->
        </div>
    </body>
</html>

